export const categories = [
{id:'animais',name:'Animais',icon:'🐾',items:[['Leão','🦁'],['Elefante','🐘'],['Girafa','🦒'],['Macaco','🐒'],['Tubarão','🦈'],['Pinguim','🐧'],['Cachorro','🐶'],['Gato','🐱'],['Cobra','🐍'],['Jacaré','🐊'],['Cavalo','🐴'],['Coruja','🦉'],['Polvo','🐙'],['Urso','🐻'],['Coelho','🐰'],['Golfinho','🐬'],['Águia','🦅'],['Tigre','🐯'],['Panda','🐼'],['Camelo','🐫'],['Rinoceronte','🦏'],['Hipopótamo','🦛'],['Galinha','🐔'],['Sapo','🐸'],['Lobo','🐺']]},
{id:'filmes',name:'Filmes e Séries',icon:'🎬',items:[['Titanic','🚢'],['Vingadores','🦸'],['Harry Potter','⚡'],['Stranger Things','🚲'],['Toy Story','🤠'],['Jurassic Park','🦖'],['Matrix','💊'],['Frozen','❄️'],['Shrek','🟢'],['Star Wars','🌌'],['Breaking Bad','🧪'],['The Walking Dead','🧟'],['Round 6','🔺'],['Game of Thrones','🐉'],['Homem-Aranha','🕷️'],['Avatar','🔵'],['O Rei Leão','🦁'],['Piratas do Caribe','🏴‍☠️'],['Friends','☕'],['The Office','🏢'],['La Casa de Papel','🎭'],['Wandinha','🖤'],['Os Simpsons','🍩'],['Senhor dos Anéis','💍'],['De Volta para o Futuro','⏰']]},
{id:'personagens',name:'Personagens',icon:'🎭',items:[['Batman','🦇'],['Superman','🦸'],['Homem-Aranha','🕷️'],['Hulk','💚'],['Mario','🍄'],['Sonic','💨'],['Mickey Mouse','🐭'],['Goku','🐉'],['Deadpool','🔴'],['Wolverine','🟡'],['Elsa','❄️'],['Darth Vader','🌌'],['Shrek','🟢'],['Pikachu','⚡'],['Scooby-Doo','🐕'],['Bob Esponja','🧽'],['Homer Simpson','🍩'],['Buzz Lightyear','🚀'],['Woody','🤠'],['Coringa','🃏'],['Thor','⚡'],['Capitão América','🛡️'],['Naruto','🍥'],['Vegeta','🐉'],['Luffy','🏴‍☠️']]},
{id:'comidas',name:'Comidas',icon:'🍕',items:[['Pizza','🍕'],['Hambúrguer','🍔'],['Sushi','🍣'],['Churrasco','🥩'],['Sorvete','🍦'],['Chocolate','🍫'],['Pipoca','🍿'],['Lasanha','🍝'],['Coxinha','🍗'],['Brigadeiro','🍬'],['Pastel','🥟'],['Hot Dog','🌭'],['Bolo','🎂'],['Batata Frita','🍟'],['Taco','🌮'],['Feijoada','🍲'],['Pão de Queijo','🧀'],['Açaí','🫐'],['Panqueca','🥞'],['Donut','🍩'],['Salada','🥗'],['Ovo','🥚'],['Bacon','🥓'],['Queijo','🧀'],['Milho','🌽']]},
{id:'profissoes',name:'Profissões',icon:'💼',items:[['Médico','🩺'],['Professor','📚'],['Bombeiro','🚒'],['Policial','👮'],['Programador','💻'],['Cozinheiro','👨‍🍳'],['Dentista','🦷'],['Piloto','✈️'],['Astronauta','🚀'],['Advogado','⚖️'],['Mecânico','🔧'],['Fotógrafo','📷'],['Veterinário','🐾'],['Arquiteto','📐'],['Eletricista','⚡'],['Jornalista','📰'],['Enfermeiro','🏥'],['Motorista','🚗'],['Padeiro','🥖'],['Ator','🎭'],['Cantor','🎤'],['Engenheiro','⚙️'],['Garçom','🍽️'],['Cabeleireiro','✂️'],['Pedreiro','🧱']]},
{id:'games',name:'Games',icon:'🎮',items:[['Minecraft','⛏️'],['Fortnite','🪂'],['GTA','🚗'],['Mario Kart','🏎️'],['The Sims','💎'],['Pokémon','⚡'],['God of War','🪓'],['Resident Evil','🧟'],['Mortal Kombat','🥊'],['Counter-Strike','🎯'],['League of Legends','⚔️'],['Among Us','🚀'],['Valheim','🛡️'],['DayZ','🧟'],['Sonic','💨'],['Zelda','🗡️'],['Call of Duty','🎖️'],['FIFA','⚽'],['The Last of Us','🍄'],['Red Dead Redemption','🤠'],['Fall Guys','🏃'],['Roblox','🧱'],['Street Fighter','🥊'],['Diablo','🔥'],['Cyberpunk 2077','🤖']]},
{id:'objetos',name:'Objetos',icon:'📦',items:[['Celular','📱'],['Televisão','📺'],['Geladeira','🧊'],['Guarda-chuva','☂️'],['Relógio','⌚'],['Óculos','👓'],['Tesoura','✂️'],['Martelo','🔨'],['Chave','🔑'],['Cadeira','🪑'],['Lâmpada','💡'],['Computador','💻'],['Fone de ouvido','🎧'],['Mochila','🎒'],['Escova de dentes','🪥'],['Panela','🍳'],['Controle remoto','🎮'],['Ventilador','💨'],['Espelho','🪞'],['Travesseiro','🛏️']]},
{id:'lugares',name:'Lugares',icon:'🌎',items:[['Praia','🏖️'],['Escola','🏫'],['Hospital','🏥'],['Aeroporto','✈️'],['Shopping','🛍️'],['Cinema','🎬'],['Restaurante','🍽️'],['Academia','🏋️'],['Supermercado','🛒'],['Igreja','⛪'],['Estádio','🏟️'],['Parque','🌳'],['Hotel','🏨'],['Delegacia','👮'],['Biblioteca','📚'],['Museu','🏛️'],['Zoológico','🦁'],['Banco','🏦'],['Padaria','🥖'],['Posto de gasolina','⛽']]},
{id:'esportes',name:'Esportes',icon:'⚽',items:[['Futebol','⚽'],['Basquete','🏀'],['Vôlei','🏐'],['Tênis','🎾'],['Natação','🏊'],['Surfe','🏄'],['Boxe','🥊'],['Skate','🛹'],['Ciclismo','🚴'],['Fórmula 1','🏎️'],['Golfe','⛳'],['Judô','🥋'],['Handebol','🤾'],['Atletismo','🏃'],['Beisebol','⚾'],['Rugby','🏉'],['Tênis de mesa','🏓'],['Esqui','⛷️'],['Hipismo','🏇'],['Futsal','⚽']]},
{id:'acoes',name:'Ações',icon:'🏃',items:[['Dormir','😴'],['Correr','🏃'],['Dançar','💃'],['Cantar','🎤'],['Nadar','🏊'],['Cozinhar','🍳'],['Dirigir','🚗'],['Chorar','😭'],['Rir','😂'],['Pular','🦘'],['Escovar os dentes','🪥'],['Tomar banho','🚿'],['Ler','📖'],['Escrever','✍️'],['Fotografar','📷'],['Pescar','🎣'],['Jogar futebol','⚽'],['Andar de bicicleta','🚲'],['Telefonar','📞'],['Aplaudir','👏']]}
];
export function getCategory(id){return categories.find(category=>category.id===id)}
export function shuffled(items){return [...items].sort(()=>Math.random()-.5)}